### ISSUE TITLE
Week 4 Peer Review of 1st Big Idea W201-5

### ISSUE THREAD

**Issue by MihirSathe1** [w201rdada/portfolio-Siilbon#1]
Nice idea, I had never put so much thought into an alarm system.  The 2nd and 3rd paragraphs of your middle section could use some reorganization and flushing out – I think you can expand this to 3-4 paragraphs so it doesn’t come off like a list.  You can add more details such as 2-3 sentences for each potential use or benefit of this algorithm – assume the reader knows less than you do about alarm systems!

In the end section, you can add some issues or consequences of the implementation of your algorithm.

**Comment by Siilbon** [comment]
I never realized how much time I spent thinking about alarm systems!  Thanks for the feedback, I added more background and examples to contextualize things.  I also ended up reorganizing my paragraphs which I think improved the flow so it is less list like.  Thanks!
