### ISSUE TITLE
Week 4 Peer Review of 1st Big Idea W201-5 from @sxc2

### ISSUE THREAD

**Issue by sxc2** [w201rdada/portfolio-Siilbon#2]
Summary:

- Use data science to train an algorithm to triage importance of alarms in manufacturing, also detect false positives, etc. 

General Comments:

- I like the dynamic prioritization of alarms section - especially the specific references to how to alarms can be more effectively routed
- very clear value proposition, well laid out

Suggestions:

- re biases and better operators - the ML algo can take the operator action as a training variable too, so we can have models specific to an individual or a group of individuals (e.g. newbie, experienced)
- small inconsistent capitalization on "Operators" in the first section, maybe an extra sentence in the intro to balance the 1:2:1 ratio

**Comment by sxc2** [comment]
@Siilbon

**Comment by Siilbon** [comment]
I corrected all the capitalization errors.  I added an idea about comparing the actions an operator takes  between the generation of an alarm and the resolution.  I really liked the idea of a common newbie baseline before the algorithm is trained on a new user.  Thanks!
